[commands]
fly = true
broadcast = true
tpa = true
back = true
home = true
warp = true
notice = true
ping = true
economy = true
economyadmin = true

[economy]
default = 5000
display_num = 15

[notice]
title = "Notice"
body = "This is a test notice\nqwq"
button = "OK"